name: TEST
on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: |
        NOT_IN_CONTAINER="this is not in the container"
        docker run --env-file "$GITHUB_ENV" debian bash -c "echo '$TEST'; echo $NOT_IN_CONTAINER"
      env: 
        TEST: "echo Test string to be passed to the container"
