name: TEST
on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2.4.0

      - name: test
        run: |
          echo "$GITHUB_ENV"
          NOT_IN_CONTAINER="this is not in the container"
          docker build -t test .
          docker run --env-file "$GITHUB_ENV" test
        env: 
          TEST: "echo Test string to be passed to the container"
