name: TEST
on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: |
        docker run --env-file "$GITHUB_ENV" debian bash -c "echo '$TEST'"
      env: 
        TEST: 'Test string to be passed to the container'
